-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- INSERT INTO days_of_week (id, value) VALUES
--   (1, 'Monday'),
--   (2, 'Tuesday'),
--   (3, 'Wednesday'),
--   (4, 'Thursday'),
--   (5, 'Friday'),
--   (6, 'Saturday'),
--   (7, 'Sunday');
